site_name: My Docs
site_url: "https://hupoboom.github.io/mymkdocs/"
site_author: hupoboom
site_description: "本网址主要用于记录学习和生活"

nav:
  - 主页: index.md
  - 人工智能: ai/index.md

  - 考研408: 408/index.md


theme:
  name: dracula